version: "3.8"

services:
    nginx:
        build: 
            dockerfile: ./docker/nginx/Dockerfile
            context: .
        ports:
            - "80:80"
        volumes:
            - .:/var/www/symfony
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/templates/:/etc/nginx/templates
        depends_on:
            - php

    php:
        build: 
            dockerfile: ./docker/php/Dockerfile
            context: .
            network: host
        volumes:
            - .:/var/www/symfony
        depends_on:
            - db

    db:
        image: mysql:8.0.33
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: editorial
            MYSQL_USER: symfony
            MYSQL_PASSWORD: secret
